image: node:13.13.0

stages:
  - build
  - deploy_aws
  - deploy

variables:
  AWS_DEFAULT_REGION: us-east-2 # The region of our S3 bucket
  BUCKET_NAME: panku.io

cache:
  paths:
    - node_modules/
    - .yarn

buildDev:  # A job to build the static website - replace it with your build methods
  stage: build
  before_script:
    - yarn install
  script:
    - yarn build
  artifacts:
    paths:
      - dist/  # This is what we want to publish, replace with your `dist` directory

deploy_aws:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest # see the note below
  stage: deploy_aws
  only:
    - master
  script:
    - aws s3 cp dist s3://${BUCKET_NAME}/ --recursive # Replace example-bucket with your bucket
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/${CI_COMMIT_REF_SLUG}  # This is the url of the bucket we saved before
    on_stop: clean_s3 # When the branch is merged, we clean up after ourself

clean_s3:
  stage: deploy
  script:
    - aws s3 rm s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive # Replace example-bucket with your bucket
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    action: stop
  when: manual
